config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/apresentacao/:number1/:number2', to: 'apresentation#home'

  get '/apresentacao/:number1/:number2/soma', to: 'apresentation#resultsoma', as: 'som'

  get '/apresentacao/:number1/:number2/sub', to: 'apresentation#resultsub', as: 'sub'

  get '/apresentacao/:number1/:number2/mul', to: 'apresentation#resultmult', as: 'mul'

  get '/apresentacao/:number1/:number2/div', to: 'apresentation#resultdiv',as: 'div'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/apresentation_controller.rb
class ApresentationController < ApplicationController
    def home
        @num1 = params[:number1].to_i
        @num2 = params[:number2].to_i
    end

    def resultsoma 
        @result   = params[:number1].to_i + params[:number2].to_i
    end 
    def resultsub
        @result   = params[:number1].to_i - params[:number2].to_i
    end 
    def resultmult 
        @result   = params[:number1].to_i * params[:number2].to_i
    end 
    def resultdiv
        @result   = params[:number1].to_i / params[:number2].to_i
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apresentation/home.html.erb
<h1>Número 1      = <%= @num1%></h1>
<h1>Número 2      = <%= @num2%></h1>

<h1>Soma          <%= @resuls%></h1>
<%= link_to 'soma', som_path%> 

<h1>Multiplicação <%= @resulm%></h1>
<%= link_to 'multiplicação', mul_path%>

<h1>Subtração     <%= @resulsub%></h1>
<%= link_to 'subtração', sub_path%>

<h1>Divisão       <%= @resuld%></h1>
<%= link_to 'divisão', div_path%>

app/views/apresentation/resultdiv.html.erb
<h1>DIVISÃO : <%= @result %></h1>

app/views/apresentation/resultmult.html.erb
<h1>MULTIPLICAÇÃO : <%= @result %></h1>

app/views/apresentation/resultsoma.html.erb
<h1>SOMA : <%= @result %></h1>

app/views/apresentation/resultsub.html.erb
<h1>SUBTRAÇÃO : <%= @result %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Aula1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
</head>

<body>
    <%= yield %>
    
</body>

</html>